name: Combined Deploy to GitHub Pages

on:
  push:
    branches: 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_main_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy Main Site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./dist
          keep_files: true

  # Задание для MTProxy
  build_mtproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd mtproxy-site
          npm install

      - name: Build
        run: |
          cd mtproxy-site
          npm run build

      - name: Deploy MTProxy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./mtproxy/dist # Убедитесь, что путь к сборке MTProxy верный
          destination_dir: mtproxy # Положит файлы в подпапку /mtproxy на хостинге
          keep_files: true
